export const GET_PRODUCT_DATA_REQUEST = 'GET_PRODUCT_DATA_REQUEST';
export const GET_PRODUCT_DATA_SUCCESS= 'GET_PRODUCT_DATA_SUCCESS';
export const GET_PRODUCT_DATA_ERROR = 'GET_PRODUCT_DATA_ERROR';

//Post Data
export const POST_PRODUCT_DATA_REQUEST = 'POST_PRODUCT_DATA_REQUEST';
export const POST_PRODUCT_DATA_SUCCESS = 'POST_PRODUCT_DATA_SUCCESS';
export const POST_PRODUCT_DATA_ERROR = 'POST_PRODUCT_DATA_ERROR';

//Delete Data
export const DELETE_PRODUCT_DATA_REQUEST = 'DELETE_PRODUCT_DATA_REQUEST';
export const DELETE_PRODUCT_DATA_SUCCESS = "DELETE_PRODUCT_DATA_SUCCESS"
export const DELETE_PRODUCT_DATA_ERROR = "DELETE_PRODUCT_DATA_ERROR"

//Update Data
export const PATCH_PRODUCT_DATA_REQUEST = "PATCH_PRODUCT_DATA_REQUEST";
export const PATCH_PRODUCT_DATA_SUCCESS = "PATCH_PRODUCT_DATA_SUCCESS";
export const PATCH_PRODUCT_DATA_ERROR = "PATCH_PRODUCT_DATA_ERROR"
